use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006008
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
Matt
Trout
mst
at
shadowcatsystems
http
James
Cheetham
jamie
Guillermo
Roditi
groditi
Karen
Etheridge
ether
Justin
Hunter
justin
Dave
Rolsky
autarch
Tomas
Doran
bobtfish
Graham
Knop
haarg
Denis
Ibaev
dionys
lib
MooseX
Types
Common
Numeric
String
